version: "3"
services:
  app:
    build: .
    image: blender-api-server:v1
    container_name: blender-api-server
    volumes:
      - ./log:/projects/BlenderApiServer/log/
    network_mode: bridge
    restart: always
  nginx:
    image: nginx:1.19.3-alpine
    container_name: blender-api-nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/p-locdev-as01.crt:/etc/ssl/p-locdev-as01.crt
      - ./certs/p-locdev-as01-decrypted.key:/etc/ssl/p-locdev-as01-decrypted.key
    network_mode: bridge
    links:
      - app
    ports:
      - 5001:8990
    restart: always
